permalink: pretty
exclude: [README.md, config.ru, Gemfile, Gemfile.lock, Rakefile, assets.yml, assets, vendor, bundle]
paginate: 10
paginate_file: index.html
assets:
  js_compressor:  uglifier
  # css_compressor: sass
